<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'About' => 'À propos',
    'Are you sure you want to delete this item?' => 'Êtes⁻vous sûr de vouloir supprimer cet élément?',
	'Contact' => 'Contact',
    'Create Task' => 'Créer tâche',
    'Create Tmuser' => 'Créer Utilisateur',
    'Create Tmuser Task' => '',
    'Delete' => 'Supprimer',
	'Home' => 'Accueil',
	'Login' => 'Connexion',
	'Logout' => 'Déconnexion',
    'Projects can be moved :' => 'Les projets peuvent être déplacés :',
    'Reset' => 'Réinitialiser',
    'Save' => 'Sauvegarder',
    'Search' => 'Recherche',
    'Task Creator' => 'Créateur',
    'Task Description' => 'Description',
    'Task Emergency' => 'Urgence',
    'Task End' => 'Fin',
    'Task ID' => 'Identifiant',
    'Task Limit' => 'Limite',
    'Task Name' => 'Nom',
    'Task Parent' => 'Tâche parente',
    'Task Priority' => 'Priorité',
    'Task Status' => 'Statut',
    'Tasks' => 'Tâches',
    'Tasks can be moved :' => 'Les tâches peuvent être déplacées :',
    'The requested page does not exist.' => 'La page demandée n\'existe pas.',
    'Tmuser First Name' => 'Prénom utilisateur',
    'Tmuser ID' => 'Identifiant',
    'Tmuser Login' => 'Login',
    'Tmuser Name' => 'Nom utilisateur',
    'Tmuser Password' => 'Mot de passe',
    'Tmuser Role' => 'Rôle',
    'Tmuser Task Order' => 'Ordre',
    'Tmuser Task Task' => 'Tâche',
    'Tmuser Task Tmuser' => 'Utilisateur',
    'Tmuser Tasks' => 'Tâches utilisateur',
    'Tmuser Type' => 'Type d\'utilisateur',
    'Tmusers' => 'Utilisateurs',
    'Update' => 'Mise à jour',
    'Update Task: mode' => 'Mise à jour tâche: mode',
    'Update Tmuser Task: mode' => 'Mise à jour tâche utilisateur: mode',
    'Update Tmuser: mode' => 'Mise à jour utilisateur: mode',
];
