<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create Task' => '',
    'Create Tmuser' => '',
    'Create Tmuser Task' => '',
    'Delete' => '',
    'Projects can be moved :' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Task Creator' => '',
    'Task Description' => '',
    'Task Emergency' => '',
    'Task End' => '',
    'Task ID' => '',
    'Task Limit' => '',
    'Task Name' => '',
    'Task Parent' => '',
    'Task Priority' => '',
    'Task Status' => '',
    'Tasks' => '',
    'Tasks can be moved :' => '',
    'The requested page does not exist.' => '',
    'Tmuser First Name' => '',
    'Tmuser ID' => '',
    'Tmuser Login' => '',
    'Tmuser Name' => '',
    'Tmuser Password' => '',
    'Tmuser Role' => '',
    'Tmuser Task Order' => '',
    'Tmuser Task Task' => '',
    'Tmuser Task Tmuser' => '',
    'Tmuser Tasks' => '',
    'Tmuser Type' => '',
    'Tmusers' => '',
    'Update' => '',
    'Update Task: mode' => '',
    'Update Tmuser Task: mode' => '',
    'Update Tmuser: mode' => '',
];
